FROM alpine:3.9
MAINTAINER James Turk <jpturk@princeton.edu>

RUN apk add --no-cache \
        postgresql-client \
         && \
    apk add --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing \
        aws-cli
